### ISSUE TITLE
[godot] Todo

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#2069]
* [x] Clean-up entire codebase
   * [x] Refactor atlas, skeleton file, skeleton data, and animation data resources.
   * [x] Add support for binary skeleton files.
   * [x] Use proper nomenclature for local vars, parameters, fields and methods.
   * [x] Clean-up includes.
   * [x] Use `nullptr` instead of `NULL`.
   * [x] Unify native object assignment and check via `SPINE_CHECK`.
   * [x] Remove empty constructors.
   * [x] General code review to identify bugs and performance issues. Fix all Clang-tidy warnings.
   * [x] `SpineBone`, `SpineSkeleton`, and `SpineSprite` have dependencies on each other and `SkeletonData` to calculate 
   * [x] Make sure strings are passed as const String &.
   * [x] Nice parameter names for bound methods.
   * [x] turn `int64_t` arguments of bound methods into `int`.
   * [x] Changing `SpineSkeletonDataResource` invalidates all skeletons and their components (bones, slots, etc.). Guard against use of disposed native objects.
* [x] `SpineSkeletonDataResource` inspector plugin
   * [x] Custom animation mixes UI
   * [x] ~Skeleton preview UI similar to spine-unity~ Use debug properties of SpineSprite instead.
* [x]  `SpineSprite` features
   * [x] Ensure setting the skeleton data works correctly with respect to signals etc.
   * [x] Batching
   * [x] User specified materials for the 4 blend modes
   * [x] ~Pre-multiplied alpha support if possible~ Currently not possible, see my proposal at https://github.com/godotengine/godot-proposals/issues/4433
   * [x] Debug rendering in editor/at runtime of bones and attachments
* [x] `SpineSlotNode` to support for attaching nodes to slots, with proper insertion in rendering order.
   * [x] Fix insertion order in `SpineSprite`
   * [x] Add materials to be applied to the slot. If user has a slot node for both before and after slot, then the after materials win out.
* [x] `SpineBoneNode` to support following or driving bones. Following is useful for collision shapes, driving is useful for terrain following etc.
   * [x] Debug rendering  
   * [x] Enable/disable
* [x] `SpineTrackEntry`
   * [x] ~Add signals~ can not be supported without memory leaks at the moment.
* [x] Remove or replace `SpineCollisionShapeProxy`.
* [x] Check if `SpineBone` Godot transforms are working as intended. I.e. shear isn't considered.
* [x] ~Add `Object::get_argument_options` implementations for classes where it makes sense, e.g. `SpineSkeleton::find_bone`, `SpineAnimationState::set_animation()`, etc. See `AnimationPlayer::get_argument_options` for an example implementation.~ Doesn't seem to be possible for properties, e.g. `SpinesSprite::animation_state`, as the underlying property object is never fetched and thus its `get_argument_options()` is never called. Sad.
* [x] `SpineAnimationTrack` to sequence animations of a SpineSprite with `AnimationPlayer`.
   * [x] `SpineAnimationTrack::update_animation_state` should only update in editor mode if the currently edited animation references the track.
   * [x] ~Try to support mixing in editor mode~ Maybe in v2
* [ ] Examples
   * [x] Hello world
   * [x] Mix and match
   * [x] Simple input
   * [x] AnimationState and TrackEntry listeners
   * [x] Mouse following
   * [x] IK following mouse cursor
   * [x] IK following hoverboard over terrain
   * [x] Slot node
   * [x] Custom materials (per skeleton, per slot via slot node)
   * [x] 2D lighting + normal map support
   * [ ] Additive blending
   * [x] Collision/overlap
   * [x] Animation player
* [x] Check for memory leaks, i.e. when removing SpineSprite instances, when unloading scenes with SpineSprite instances, when removing SpineSprites that have animations active and may leak the listener wrappers in their track entries.
* [x] Ensure compatibility with 3.x and 4.x
   * [x] Normal maps via `CanvasTexture`, which combines diffuse and normal map in 4.x.
   * [ ] Sync 3.x examples with 4.x
* [x] Make sure all classes visible in editor have icons
* [x] Pre-built Engine binaries and export templates. Build using GitHub Actions.
* [x] Documentation on website and in module
   * [x] Note that batching is required for great performance, both in game and in the editor. Setting is hidden behind "Advanced Options" in 4.x.

## 4.x bugs
- [x] Loading animation-player.tscn results in `ERROR: Attempt to disconnect a nonexistent connection from '[Animation:-9223370711437888444]'. Signal: 'tracks_changed', callable: 'AnimationPlayer::_animation_changed'.
   at: (core\object\object.cpp:1408)` when setting up the `AnimationPlayer` instances of the `SpineAnimationTrack` instances. We remove the existing animation library from each player, which triggers `AnimationPlayer::_unref_anim()`, which tries to disconnect a signal. However, the corresponding `AnimationPlayer::_ref_anim()` isn't called before that anywhere. In fact, it's not called at all in the entire codebase. See https://github.com/godotengine/godot/issues/60566
- [x] When having a scene with an `AnimationPlayer` open, like `animation-player.tscn`, saving the scene will result in ```ERROR: Condition "!playback.current.from" is true.
   at: AnimationPlayer::seek (scene\animation\animation_player.cpp:1719)
ERROR: Condition "!animation_set.has(p_anim)" is true.
   at: AnimationPlayer::set_assigned_animation (scene\animation\animation_player.cpp:1673)``` See https://github.com/godotengine/godot/issues/60564 and my PR at https://github.com/godotengine/godot/pull/60565
- [x] Currently (May 31st 2022), nothing renders...

## V2
* Two color tint (currently not possible due to fixed vertex format with which we can't pass additional color)
*  `SpineRagDoll`, takes a root bone, then generates child `SpinePhysicsBoneNode` and `PinJoint2D` nodes. 
   * Enable/disable

**Comment by tarragonfly** [comment]
Can't compile Godot 3.4 branch source with latest 4.2 Godot runtime:

`
[Initial build] Compiling ==> modules\spine_godot\spine-cpp\src\spine\ClippingAttachment.cpp
BoundingBoxAttachment.cpp
modules\spine_godot\spine-cpp\src\spine\BoneData.cpp(30): fatal error C1083: Cannot open include file: 'spine/BoneData.h': No such file or directory
[Initial build] Compiling ==> modules\spine_godot\spine-cpp\src\spine\ColorTimeline.cpp
ClippingAttachment.cpp
modules\spine_godot\spine-cpp\src\spine\BoundingBoxAttachment.cpp(30): fatal error C1083: Cannot open include file: 'spine/BoundingBoxAttachment.h': No such file or directory
ColorTimeline.cpp
modules\spine_godot\spine-cpp\src\spine\ClippingAttachment.cpp(30): fatal error C1083: Cannot open include file: 'spine/ClippingAttachment.h': No such file or directory
modules\spine_godot\spine-cpp\src\spine\ColorTimeline.cpp(30): fatal error C1083: Cannot open include file: 'spine/ColorTimeline.h': No such file or directory
scons: *** [modules\spine_godot\spine-cpp\src\spine\Animation.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\AnimationState.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\AnimationStateData.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\Atlas.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\AtlasAttachmentLoader.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\Attachment.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\AttachmentLoader.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\AttachmentTimeline.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\Bone.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\BoneData.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\BoundingBoxAttachment.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\ClippingAttachment.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\ColorTimeline.windows.tools.64.obj] Error 2
scons: building terminated because of errors.
[Time elapsed: 00:00:33.050]`

**Comment by badlogic** [comment]
What OS/compiler? How did you run setup.sh or setup.bat? They need to be
run with spine-runtimes/spine-godot as the working directory for now.

**Comment by Calinou** [comment]
>  Note that batching is required for great performance, both in game and in the editor. Setting is hidden behind "Advanced Options" in 4.x.

2D batching isn't implemented in the Vulkan renderer yet. Since the CPU cost of individual draw calls is lower than in OpenGL, there isn't as much benefit to having batching compared to OpenGL (yet the added complexity in the codebase is identical, if not greater). Also, the Vulkan renderer already uses instancing in both 2D and 3D, so having actual batching would probably not make much of a difference in practice. This is especially the case when you consider other effects in place such as lights, shaders, etc.

That said, [2D batching is supported in the 4.x OpenGL renderer](https://github.com/godotengine/godot/pull/55656). It's supposed to be enabled by default – if not, it's a bug.

**Comment by badlogic** [comment]
Thanks for chiming in here. I see a quite heavy performance decrease on the 4.x Vulkan renderer for the same exact rendering code path on my end. Haven't investigated yet where it goes wrong inside the Vulkan renderer. But as you said, draw call overhead should be a lot better on Vulkan, so I'm a bit puzzled why I'm seeing the exact oposite: unbatched Godot 3.x OpenGL (ES) 2 and 3 rendering is faster than unbatched Godot 4.x Vulkan rendering.

**Comment by rinvars** [comment]
I offer a kingdom and a princess (and/or a prince) for a pre-made outline shader in Godot. I've been really struggling to get something usable in Unity's URP even with the pre-made outline only shader which has been challenging. Too many things in Unity lately have become challenging.

**Comment by CDOccc** [comment]
Godot 4.x 的 CanvasItem Shader 已经提供：CUSTOM0 / CUSTOM1 自定义顶点数据通道，可以把额外数据从 Mesh（网格）送进 Shader。
Two-color Tinting这个功能是不是可以实现一下？
